### ISSUE TITLE
Bienvenida

### ISSUE THREAD

**Issue by dblascom** [dblascom/IWVG.SwC.DavidBlasco#1]
Hola!! @TamaraJDz @robiscjuan @albertobricio 

He creado [wiki ](https://github.com/dblascom/IWVG.SwC.DavidBlasco/wiki)y [planificación](https://github.com/dblascom/IWVG.SwC.DavidBlasco/milestones) del proyecto. Podeis ver lo que tengo previsto asignaros y los plazos. Si veis algo raro o queréis cambiar algo me lo decís. Soy un buen jefe :+1: 

Estoy configurando software Eclipse y Maven en PC de casa.

Cuando tengo todo listo os enviaré los tickets.

Tened paciencia conmigo que estoy un poco verde con el JAVA y esto es todo nuevo para mi....

Gracias!
David B. 

**NOTA**: Supongo esto funciona como un email. Confirmadme la recepción y así lo confirmo.

**Comment by robiscjuan** [comment]
Perfecto David.

Efectivamente llega al correo una notificación.

Un saludo,
Juan.

**Comment by dblascom** [comment]
Genial Juan. He tenido un breve contacto con BaseCamp y esto parece funcionar parecido. Gracias!
