### ISSUE TITLE
Ampliación P2 - 2: Ampliar la Clase Fraction con el método suma

### ISSUE THREAD

**Issue by dblascom** [dblascom/IWVG.SwC.DavidBlasco#10]
Hola @robiscjuan

Tu segunda tarea consiste en implementar el método suma de la clase Fraction

Más información sobre tus tareas [aquí](https://github.com/dblascom/IWVG.SwC.DavidBlasco/wiki/Tareas-P2)

Fecha entrega: 01/10/2016

**Comment by robiscjuan** [comment]
Ya lo tienes todo. Un saludo.

<img width="556" alt="ramafinal" src="https://cloud.githubusercontent.com/assets/4128515/18965478/b0a9d14c-867d-11e6-9096-104ceb93a87a.PNG">
