### ISSUE TITLE
Ampliación P2 - 1: Ampliar la Clase Point con un método.

### ISSUE THREAD

**Issue by dblascom** [dblascom/IWVG.SwC.DavidBlasco#9]
Hola @robiscjuan

Tu primera tarea consiste en modificar los atributos X e Y de la clase Point

Más información sobre tus tareas [aquí](https://github.com/dblascom/IWVG.SwC.DavidBlasco/wiki/Tareas-P2)

Fecha entrega: 01/10/2016

**Comment by robiscjuan** [comment]
Hecho!

<img width="606" alt="rama" src="https://cloud.githubusercontent.com/assets/4128515/18965032/bc16893c-867b-11e6-837f-ac115411fb83.PNG">

**Comment by dblascom** [comment]
Genial!. Tienes un 1.
El pantallazo buena idea.
